version: 2
jobs:
  pytest-2.7:
    docker:
      - image: python:2.7
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: make test
  pytest:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: make test
  install:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run: python setup.py install
      - run: mackup --help
  flake8:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run: pip install flake8
      - run: flake8
  mypy:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run: pip install codecov
      - run: pip install -r requirements.txt
      - run: pip install mypy lxml
      - run: mypy --ignore-missing-imports --cobertura-xml-report ./ --python-version 3.7 mackup
      - run: mv cobertura.xml coverage.xml
      - run: codecov
  mypy-2.7:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run: pip install codecov
      - run: pip install -r requirements.txt
      - run: pip install mypy lxml
      - run: mkdir build
      - run: mypy --ignore-missing-imports --cobertura-xml-report ./ --python-version 2.7 mackup
      - run: mv cobertura.xml coverage.xml
      - run: codecov
  mdl:
    docker:
      - image: rsrchboy/mdl
    steps:
      - checkout
      - run: mdl .

workflows:
  version: 2
  mackup:
    jobs:
      - pytest-2.7
      - pytest
      - install
      - flake8
      - mdl
      - mypy
      - mypy-2.7
